[package]
name = "multicalc"
version = "0.3.0"
authors = ["akathail <anmolkathail@gmail.com>"]
edition = "2021"
description = "Rust scientific computing for single and multi-variable calculus"
repository = "https://github.com/kmolan/multicalc-rust"
license = "MIT"
readme = "README.md"
#documentation = TODO
keywords = ["Math", "Science", "Calculus", "Differentiation", "Integration"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
num-complex = "0.4.6"

[dev-dependencies]
rand = "0.8"

[features]
default = ["std"]
std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
