// GENERATED by `cargo run -p multicalc-oracle --bin gen_smoke_fixtures`. Do not edit.
// Goldens for the on-target smoke checks, taken bit-exact from tools/oracle/fixtures/v1.
// SVD golden: linalg/svd_3x3. LM golden: optimization/rosenbrock.
#![allow(clippy::unreadable_literal)]

/// Input matrix `A` (row-major 3×3) for the SVD check, from linalg/svd_3x3.
pub const SVD_3X3_INPUT: [[f64; 3]; 3] = [
    [
        f64::from_bits(0x3fe2763f5d1ce592),
        f64::from_bits(0xbfd8d914ad03f36c),
        f64::from_bits(0x3fb25b646e3094b0),
    ],
    [
        f64::from_bits(0x3fe622dfc7a9f89e),
        f64::from_bits(0x3fd9e223541c2004),
        f64::from_bits(0xbfe62d633c4f7204),
    ],
    [
        f64::from_bits(0xbfef15212fa242ca),
        f64::from_bits(0x3f86822382d5fe80),
        f64::from_bits(0xbfe18282767f4e98),
    ],
];

/// Expected singular values of `SVD_3X3_INPUT`, descending.
pub const SVD_3X3_SINGULAR_VALUES: [f64; 3] = [
    f64::from_bits(0x3ff5400d80d4d692),
    f64::from_bits(0x3feefaabc5b78ecf),
    f64::from_bits(0x3fd907ffa3d1e959),
];

/// Comparison tolerance for the SVD check (from the fixture's f64 tolerance).
pub const SVD_3X3_ABS: f64 = 1e-11;
pub const SVD_3X3_REL: f64 = 1e-10;

/// Initial guess for the Rosenbrock least-squares fit, from optimization/rosenbrock.
pub const ROSENBROCK_X0: [f64; 2] = [
    f64::from_bits(0xbff3333333333333),
    f64::from_bits(0x3ff0000000000000),
];

/// Expected minimizer of the Rosenbrock fit.
pub const ROSENBROCK_SOLUTION: [f64; 2] = [
    f64::from_bits(0x3ff0000000000000),
    f64::from_bits(0x3ff0000000000000),
];

/// Comparison tolerance for the Rosenbrock check (from the fixture's f64 tolerance).
pub const ROSENBROCK_ABS: f64 = 1e-7;
pub const ROSENBROCK_REL: f64 = 1e-6;
