// GENERATED by `cargo run -p multicalc-qa --bin gen_model_source`. Do not edit.
// Source: third_party/menagerie/franka_emika_panda/panda.xml, the world down to the hand frame.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::unreadable_literal)]
#![allow(dead_code)]

use multicalc::kinematics::{Joint, JointParent, KinematicTree};
use multicalc::linear_algebra::Vector;
use multicalc::spatial::{Quaternion, SE3, SO3};

/// The Franka Panda arm: the seven turning joints from the base up to the hand, with the base and the hand as welds.
pub fn franka_panda_arm() -> KinematicTree<9, 9, f32> {
    let mut tree = KinematicTree::<9, 9, f32>::new();
    // link0
    tree.push(
        Joint::fixed(pose([0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0.0])),
        JointParent::World,
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link1
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, 0.0, 0.333], [1.0, 0.0, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(0),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link2
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, 0.0, 0.0], [0.70710677, -0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-1.7628, 1.7628)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(1),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link3
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, -0.316, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(2),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link4
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0825, 0.0, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-3.0718, -0.0698)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(3),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link5
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([-0.0825, 0.384, 0.0], [0.70710677, -0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(4),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link6
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, 0.0, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-0.0175, 3.7525)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(5),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link7
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.088, 0.0, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(6),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // hand
    tree.push(
        Joint::fixed(pose([0.0, 0.0, 0.107], [0.92387956, 0.0, 0.0, -0.38268343])),
        JointParent::Joint(7),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    tree
}

/// Where a joint sits and how it is turned, from the numbers the model file gave.
fn pose(translation: [f32; 3], quaternion: [f32; 4]) -> SE3<f32> {
    let turn = Quaternion::new(quaternion[0], quaternion[1], quaternion[2], quaternion[3])
        .try_normalized()
        .unwrap_or_else(|| unreachable!("the model this was written from was checked"));
    SE3::from_parts(SO3::from_quaternion(turn), Vector::new(translation))
}
