// GENERATED by `cargo run -p multicalc-qa --bin gen_model_source`. Do not edit.
// Source: third_party/menagerie/franka_emika_panda/panda.xml, the world down to the hand frame.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::unreadable_literal)]
#![allow(dead_code)]

use multicalc::dynamics::ArticulatedBody;
use multicalc::kinematics::{Joint, JointParent, KinematicTree};
use multicalc::linear_algebra::{Matrix, Vector};
use multicalc::spatial::{Quaternion, SE3, SO3, SpatialInertia};

/// The Franka Panda arm: the seven turning joints from the base up to the hand, with the base and the hand as welds.
pub fn franka_panda_arm() -> KinematicTree<9, 9, f32> {
    let mut tree = KinematicTree::<9, 9, f32>::new();
    // link0
    tree.push(
        Joint::fixed(pose([0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0.0])),
        JointParent::World,
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link1
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, 0.0, 0.333], [1.0, 0.0, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(0),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link2
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, 0.0, 0.0], [0.70710677, -0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-1.7628, 1.7628)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(1),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link3
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, -0.316, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(2),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link4
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0825, 0.0, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-3.0718, -0.0698)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(3),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link5
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([-0.0825, 0.384, 0.0], [0.70710677, -0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(4),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link6
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.0, 0.0, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-0.0175, 3.7525)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(5),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // link7
    tree.push(
        Joint::revolute(Vector::new([0.0, 0.0, 1.0]), pose([0.088, 0.0, 0.0], [0.70710677, 0.70710677, 0.0, 0.0]))
            .with_anchor(Vector::new([0.0, 0.0, 0.0]))
            .with_limits(-2.8973, 2.8973)
            .with_zero_offset(0.0)
            .with_armature(0.1)
            .with_damping(1.0)
            .with_friction_loss(0.0),
        JointParent::Joint(6),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    // hand
    tree.push(
        Joint::fixed(pose([0.0, 0.0, 0.107], [0.92387956, 0.0, 0.0, -0.38268343])),
        JointParent::Joint(7),
    )
    .unwrap_or_else(|_| unreachable!("the model this was written from was checked"));
    tree
}

/// The same model with its stated mass properties and Earth gravity in world axes.
pub fn franka_panda_arm_body() -> ArticulatedBody<9, 9, f32> {
    let tree = franka_panda_arm();
    let inertias = [
        // link0
        Some(inertia(0.629769, [-0.041018, -0.00014, 0.049974], [[0.00315, 8.2904e-7, 0.00015], [8.2904e-7, 0.00388, 8.2299e-6], [0.00015, 8.2299e-6, 0.004285]])),
        // link1
        Some(inertia(4.970684, [0.003875, 0.002081, -0.04762], [[0.70337, -0.000139, 0.006772], [-0.000139, 0.70661, 0.019169], [0.006772, 0.019169, 0.009117]])),
        // link2
        Some(inertia(0.646926, [-0.003141, -0.02872, 0.003495], [[0.007962, -0.003925, 0.010254], [-0.003925, 0.02811, 0.000704], [0.010254, 0.000704, 0.025995]])),
        // link3
        Some(inertia(3.228604, [0.027518, 0.039252, -0.066502], [[0.037242, -0.004761, -0.011396], [-0.004761, 0.036155, -0.012805], [-0.011396, -0.012805, 0.01083]])),
        // link4
        Some(inertia(3.587895, [-0.05317, 0.104419, 0.027454], [[0.025853, 0.007796, -0.001332], [0.007796, 0.019552, 0.008641], [-0.001332, 0.008641, 0.028323]])),
        // link5
        Some(inertia(1.225946, [-0.011953, 0.041065, -0.038437], [[0.035549, -0.002117, -0.004037], [-0.002117, 0.029474, 0.000229], [-0.004037, 0.000229, 0.008627]])),
        // link6
        Some(inertia(1.666555, [0.060149, -0.014117, -0.010517], [[0.001964, 0.000109, -0.001158], [0.000109, 0.004354, 0.000341], [-0.001158, 0.000341, 0.005433]])),
        // link7
        Some(inertia(0.735522, [0.010517, -0.004252, 0.061597], [[0.012516, -0.000428, -0.001196], [-0.000428, 0.010027, -0.000741], [-0.001196, -0.000741, 0.004815]])),
        // hand
        Some(inertia(0.73, [-0.01, 0.0, 0.03], [[0.001, 0.0, 0.0], [0.0, 0.0025, 0.0], [0.0, 0.0, 0.0017]])),
    ];
    ArticulatedBody::new(tree, &inertias, Vector::new([0.0, 0.0, -9.81]))
        .unwrap_or_else(|_| unreachable!("the model this was written from was checked"))
}

/// A body's mass properties, from the numbers the model file gave.
fn inertia(mass: f32, center: [f32; 3], rotational: [[f32; 3]; 3]) -> SpatialInertia<f32> {
    SpatialInertia::new(mass, Vector::new(center), Matrix::new(rotational))
        .unwrap_or_else(|_| unreachable!("the model this was written from was checked"))
}

/// Where a joint sits and how it is turned, from the numbers the model file gave.
fn pose(translation: [f32; 3], quaternion: [f32; 4]) -> SE3<f32> {
    let turn = Quaternion::new(quaternion[0], quaternion[1], quaternion[2], quaternion[3])
        .try_normalized()
        .unwrap_or_else(|| unreachable!("the model this was written from was checked"));
    SE3::from_parts(SO3::from_quaternion(turn), Vector::new(translation))
}
