// This file is auto-generated. Do not edit manually.

use crate::utils::error_codes::GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE;

use crate::numerical_integration::mode::GaussianQuadratureMethod;

use crate::gaussian_tables::hermite::*;
use crate::gaussian_tables::laguerre::*;
use crate::gaussian_tables::legendre::*;

pub fn get_abscissae(
    method: GaussianQuadratureMethod,
    n: usize,
) -> Result<&'static [f64], &'static str> {
    match method {
        GaussianQuadratureMethod::GaussLaguerre => match n {
            1 => Ok(&LAGUERRE_ABSCISSA_1),
            2 => Ok(&LAGUERRE_ABSCISSA_2),
            3 => Ok(&LAGUERRE_ABSCISSA_3),
            4 => Ok(&LAGUERRE_ABSCISSA_4),
            5 => Ok(&LAGUERRE_ABSCISSA_5),
            6 => Ok(&LAGUERRE_ABSCISSA_6),
            7 => Ok(&LAGUERRE_ABSCISSA_7),
            8 => Ok(&LAGUERRE_ABSCISSA_8),
            9 => Ok(&LAGUERRE_ABSCISSA_9),
            10 => Ok(&LAGUERRE_ABSCISSA_10),
            11 => Ok(&LAGUERRE_ABSCISSA_11),
            12 => Ok(&LAGUERRE_ABSCISSA_12),
            13 => Ok(&LAGUERRE_ABSCISSA_13),
            14 => Ok(&LAGUERRE_ABSCISSA_14),
            15 => Ok(&LAGUERRE_ABSCISSA_15),
            16 => Ok(&LAGUERRE_ABSCISSA_16),
            17 => Ok(&LAGUERRE_ABSCISSA_17),
            18 => Ok(&LAGUERRE_ABSCISSA_18),
            19 => Ok(&LAGUERRE_ABSCISSA_19),
            20 => Ok(&LAGUERRE_ABSCISSA_20),
            21 => Ok(&LAGUERRE_ABSCISSA_21),
            22 => Ok(&LAGUERRE_ABSCISSA_22),
            23 => Ok(&LAGUERRE_ABSCISSA_23),
            24 => Ok(&LAGUERRE_ABSCISSA_24),
            25 => Ok(&LAGUERRE_ABSCISSA_25),
            26 => Ok(&LAGUERRE_ABSCISSA_26),
            27 => Ok(&LAGUERRE_ABSCISSA_27),
            28 => Ok(&LAGUERRE_ABSCISSA_28),
            29 => Ok(&LAGUERRE_ABSCISSA_29),
            30 => Ok(&LAGUERRE_ABSCISSA_30),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
        GaussianQuadratureMethod::GaussHermite => match n {
            1 => Ok(&HERMITE_ABSCISSA_1),
            2 => Ok(&HERMITE_ABSCISSA_2),
            3 => Ok(&HERMITE_ABSCISSA_3),
            4 => Ok(&HERMITE_ABSCISSA_4),
            5 => Ok(&HERMITE_ABSCISSA_5),
            6 => Ok(&HERMITE_ABSCISSA_6),
            7 => Ok(&HERMITE_ABSCISSA_7),
            8 => Ok(&HERMITE_ABSCISSA_8),
            9 => Ok(&HERMITE_ABSCISSA_9),
            10 => Ok(&HERMITE_ABSCISSA_10),
            11 => Ok(&HERMITE_ABSCISSA_11),
            12 => Ok(&HERMITE_ABSCISSA_12),
            13 => Ok(&HERMITE_ABSCISSA_13),
            14 => Ok(&HERMITE_ABSCISSA_14),
            15 => Ok(&HERMITE_ABSCISSA_15),
            16 => Ok(&HERMITE_ABSCISSA_16),
            17 => Ok(&HERMITE_ABSCISSA_17),
            18 => Ok(&HERMITE_ABSCISSA_18),
            19 => Ok(&HERMITE_ABSCISSA_19),
            20 => Ok(&HERMITE_ABSCISSA_20),
            21 => Ok(&HERMITE_ABSCISSA_21),
            22 => Ok(&HERMITE_ABSCISSA_22),
            23 => Ok(&HERMITE_ABSCISSA_23),
            24 => Ok(&HERMITE_ABSCISSA_24),
            25 => Ok(&HERMITE_ABSCISSA_25),
            26 => Ok(&HERMITE_ABSCISSA_26),
            27 => Ok(&HERMITE_ABSCISSA_27),
            28 => Ok(&HERMITE_ABSCISSA_28),
            29 => Ok(&HERMITE_ABSCISSA_29),
            30 => Ok(&HERMITE_ABSCISSA_30),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
        GaussianQuadratureMethod::GaussLegendre => match n {
            1 => Ok(&LEGENDRE_ABSCISSA_1),
            2 => Ok(&LEGENDRE_ABSCISSA_2),
            3 => Ok(&LEGENDRE_ABSCISSA_3),
            4 => Ok(&LEGENDRE_ABSCISSA_4),
            5 => Ok(&LEGENDRE_ABSCISSA_5),
            6 => Ok(&LEGENDRE_ABSCISSA_6),
            7 => Ok(&LEGENDRE_ABSCISSA_7),
            8 => Ok(&LEGENDRE_ABSCISSA_8),
            9 => Ok(&LEGENDRE_ABSCISSA_9),
            10 => Ok(&LEGENDRE_ABSCISSA_10),
            11 => Ok(&LEGENDRE_ABSCISSA_11),
            12 => Ok(&LEGENDRE_ABSCISSA_12),
            13 => Ok(&LEGENDRE_ABSCISSA_13),
            14 => Ok(&LEGENDRE_ABSCISSA_14),
            15 => Ok(&LEGENDRE_ABSCISSA_15),
            16 => Ok(&LEGENDRE_ABSCISSA_16),
            17 => Ok(&LEGENDRE_ABSCISSA_17),
            18 => Ok(&LEGENDRE_ABSCISSA_18),
            19 => Ok(&LEGENDRE_ABSCISSA_19),
            20 => Ok(&LEGENDRE_ABSCISSA_20),
            21 => Ok(&LEGENDRE_ABSCISSA_21),
            22 => Ok(&LEGENDRE_ABSCISSA_22),
            23 => Ok(&LEGENDRE_ABSCISSA_23),
            24 => Ok(&LEGENDRE_ABSCISSA_24),
            25 => Ok(&LEGENDRE_ABSCISSA_25),
            26 => Ok(&LEGENDRE_ABSCISSA_26),
            27 => Ok(&LEGENDRE_ABSCISSA_27),
            28 => Ok(&LEGENDRE_ABSCISSA_28),
            29 => Ok(&LEGENDRE_ABSCISSA_29),
            30 => Ok(&LEGENDRE_ABSCISSA_30),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
    }
}

pub fn get_weights(
    method: GaussianQuadratureMethod,
    n: usize,
) -> Result<&'static [f64], &'static str> {
    match method {
        GaussianQuadratureMethod::GaussLaguerre => match n {
            1 => Ok(&LAGUERRE_WEIGHT_1),
            2 => Ok(&LAGUERRE_WEIGHT_2),
            3 => Ok(&LAGUERRE_WEIGHT_3),
            4 => Ok(&LAGUERRE_WEIGHT_4),
            5 => Ok(&LAGUERRE_WEIGHT_5),
            6 => Ok(&LAGUERRE_WEIGHT_6),
            7 => Ok(&LAGUERRE_WEIGHT_7),
            8 => Ok(&LAGUERRE_WEIGHT_8),
            9 => Ok(&LAGUERRE_WEIGHT_9),
            10 => Ok(&LAGUERRE_WEIGHT_10),
            11 => Ok(&LAGUERRE_WEIGHT_11),
            12 => Ok(&LAGUERRE_WEIGHT_12),
            13 => Ok(&LAGUERRE_WEIGHT_13),
            14 => Ok(&LAGUERRE_WEIGHT_14),
            15 => Ok(&LAGUERRE_WEIGHT_15),
            16 => Ok(&LAGUERRE_WEIGHT_16),
            17 => Ok(&LAGUERRE_WEIGHT_17),
            18 => Ok(&LAGUERRE_WEIGHT_18),
            19 => Ok(&LAGUERRE_WEIGHT_19),
            20 => Ok(&LAGUERRE_WEIGHT_20),
            21 => Ok(&LAGUERRE_WEIGHT_21),
            22 => Ok(&LAGUERRE_WEIGHT_22),
            23 => Ok(&LAGUERRE_WEIGHT_23),
            24 => Ok(&LAGUERRE_WEIGHT_24),
            25 => Ok(&LAGUERRE_WEIGHT_25),
            26 => Ok(&LAGUERRE_WEIGHT_26),
            27 => Ok(&LAGUERRE_WEIGHT_27),
            28 => Ok(&LAGUERRE_WEIGHT_28),
            29 => Ok(&LAGUERRE_WEIGHT_29),
            30 => Ok(&LAGUERRE_WEIGHT_30),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
        GaussianQuadratureMethod::GaussHermite => match n {
            1 => Ok(&HERMITE_WEIGHT_1),
            2 => Ok(&HERMITE_WEIGHT_2),
            3 => Ok(&HERMITE_WEIGHT_3),
            4 => Ok(&HERMITE_WEIGHT_4),
            5 => Ok(&HERMITE_WEIGHT_5),
            6 => Ok(&HERMITE_WEIGHT_6),
            7 => Ok(&HERMITE_WEIGHT_7),
            8 => Ok(&HERMITE_WEIGHT_8),
            9 => Ok(&HERMITE_WEIGHT_9),
            10 => Ok(&HERMITE_WEIGHT_10),
            11 => Ok(&HERMITE_WEIGHT_11),
            12 => Ok(&HERMITE_WEIGHT_12),
            13 => Ok(&HERMITE_WEIGHT_13),
            14 => Ok(&HERMITE_WEIGHT_14),
            15 => Ok(&HERMITE_WEIGHT_15),
            16 => Ok(&HERMITE_WEIGHT_16),
            17 => Ok(&HERMITE_WEIGHT_17),
            18 => Ok(&HERMITE_WEIGHT_18),
            19 => Ok(&HERMITE_WEIGHT_19),
            20 => Ok(&HERMITE_WEIGHT_20),
            21 => Ok(&HERMITE_WEIGHT_21),
            22 => Ok(&HERMITE_WEIGHT_22),
            23 => Ok(&HERMITE_WEIGHT_23),
            24 => Ok(&HERMITE_WEIGHT_24),
            25 => Ok(&HERMITE_WEIGHT_25),
            26 => Ok(&HERMITE_WEIGHT_26),
            27 => Ok(&HERMITE_WEIGHT_27),
            28 => Ok(&HERMITE_WEIGHT_28),
            29 => Ok(&HERMITE_WEIGHT_29),
            30 => Ok(&HERMITE_WEIGHT_30),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
        GaussianQuadratureMethod::GaussLegendre => match n {
            1 => Ok(&LEGENDRE_WEIGHT_1),
            2 => Ok(&LEGENDRE_WEIGHT_2),
            3 => Ok(&LEGENDRE_WEIGHT_3),
            4 => Ok(&LEGENDRE_WEIGHT_4),
            5 => Ok(&LEGENDRE_WEIGHT_5),
            6 => Ok(&LEGENDRE_WEIGHT_6),
            7 => Ok(&LEGENDRE_WEIGHT_7),
            8 => Ok(&LEGENDRE_WEIGHT_8),
            9 => Ok(&LEGENDRE_WEIGHT_9),
            10 => Ok(&LEGENDRE_WEIGHT_10),
            11 => Ok(&LEGENDRE_WEIGHT_11),
            12 => Ok(&LEGENDRE_WEIGHT_12),
            13 => Ok(&LEGENDRE_WEIGHT_13),
            14 => Ok(&LEGENDRE_WEIGHT_14),
            15 => Ok(&LEGENDRE_WEIGHT_15),
            16 => Ok(&LEGENDRE_WEIGHT_16),
            17 => Ok(&LEGENDRE_WEIGHT_17),
            18 => Ok(&LEGENDRE_WEIGHT_18),
            19 => Ok(&LEGENDRE_WEIGHT_19),
            20 => Ok(&LEGENDRE_WEIGHT_20),
            21 => Ok(&LEGENDRE_WEIGHT_21),
            22 => Ok(&LEGENDRE_WEIGHT_22),
            23 => Ok(&LEGENDRE_WEIGHT_23),
            24 => Ok(&LEGENDRE_WEIGHT_24),
            25 => Ok(&LEGENDRE_WEIGHT_25),
            26 => Ok(&LEGENDRE_WEIGHT_26),
            27 => Ok(&LEGENDRE_WEIGHT_27),
            28 => Ok(&LEGENDRE_WEIGHT_28),
            29 => Ok(&LEGENDRE_WEIGHT_29),
            30 => Ok(&LEGENDRE_WEIGHT_30),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
    }
}
