// This file was auto-generated using scripts/build_gaussian_integration_tables.py
// Do not edit manually.

use crate::utils::error_codes::GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE;

use crate::numerical_integration::mode::GaussianQuadratureMethod;

use crate::gaussian_tables::laguerre::*;
use crate::gaussian_tables::hermite::*;
use crate::gaussian_tables::legendre::*;

pub const MAX_GAUSS_TABLE_ORDER: usize = 30;

pub fn get_weight_and_abscissa(method: GaussianQuadratureMethod, order: usize, index: usize) -> Result<(f64, f64), &'static str> {
    match method {
        GaussianQuadratureMethod::GaussLaguerre => match order {
            1 => Ok((LAGUERRE_WEIGHT_1[index], LAGUERRE_ABSCISSA_1[index])),
            2 => Ok((LAGUERRE_WEIGHT_2[index], LAGUERRE_ABSCISSA_2[index])),
            3 => Ok((LAGUERRE_WEIGHT_3[index], LAGUERRE_ABSCISSA_3[index])),
            4 => Ok((LAGUERRE_WEIGHT_4[index], LAGUERRE_ABSCISSA_4[index])),
            5 => Ok((LAGUERRE_WEIGHT_5[index], LAGUERRE_ABSCISSA_5[index])),
            6 => Ok((LAGUERRE_WEIGHT_6[index], LAGUERRE_ABSCISSA_6[index])),
            7 => Ok((LAGUERRE_WEIGHT_7[index], LAGUERRE_ABSCISSA_7[index])),
            8 => Ok((LAGUERRE_WEIGHT_8[index], LAGUERRE_ABSCISSA_8[index])),
            9 => Ok((LAGUERRE_WEIGHT_9[index], LAGUERRE_ABSCISSA_9[index])),
            10 => Ok((LAGUERRE_WEIGHT_10[index], LAGUERRE_ABSCISSA_10[index])),
            11 => Ok((LAGUERRE_WEIGHT_11[index], LAGUERRE_ABSCISSA_11[index])),
            12 => Ok((LAGUERRE_WEIGHT_12[index], LAGUERRE_ABSCISSA_12[index])),
            13 => Ok((LAGUERRE_WEIGHT_13[index], LAGUERRE_ABSCISSA_13[index])),
            14 => Ok((LAGUERRE_WEIGHT_14[index], LAGUERRE_ABSCISSA_14[index])),
            15 => Ok((LAGUERRE_WEIGHT_15[index], LAGUERRE_ABSCISSA_15[index])),
            16 => Ok((LAGUERRE_WEIGHT_16[index], LAGUERRE_ABSCISSA_16[index])),
            17 => Ok((LAGUERRE_WEIGHT_17[index], LAGUERRE_ABSCISSA_17[index])),
            18 => Ok((LAGUERRE_WEIGHT_18[index], LAGUERRE_ABSCISSA_18[index])),
            19 => Ok((LAGUERRE_WEIGHT_19[index], LAGUERRE_ABSCISSA_19[index])),
            20 => Ok((LAGUERRE_WEIGHT_20[index], LAGUERRE_ABSCISSA_20[index])),
            21 => Ok((LAGUERRE_WEIGHT_21[index], LAGUERRE_ABSCISSA_21[index])),
            22 => Ok((LAGUERRE_WEIGHT_22[index], LAGUERRE_ABSCISSA_22[index])),
            23 => Ok((LAGUERRE_WEIGHT_23[index], LAGUERRE_ABSCISSA_23[index])),
            24 => Ok((LAGUERRE_WEIGHT_24[index], LAGUERRE_ABSCISSA_24[index])),
            25 => Ok((LAGUERRE_WEIGHT_25[index], LAGUERRE_ABSCISSA_25[index])),
            26 => Ok((LAGUERRE_WEIGHT_26[index], LAGUERRE_ABSCISSA_26[index])),
            27 => Ok((LAGUERRE_WEIGHT_27[index], LAGUERRE_ABSCISSA_27[index])),
            28 => Ok((LAGUERRE_WEIGHT_28[index], LAGUERRE_ABSCISSA_28[index])),
            29 => Ok((LAGUERRE_WEIGHT_29[index], LAGUERRE_ABSCISSA_29[index])),
            30 => Ok((LAGUERRE_WEIGHT_30[index], LAGUERRE_ABSCISSA_30[index])),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
        GaussianQuadratureMethod::GaussHermite => match order {
            1 => Ok((HERMITE_WEIGHT_1[index], HERMITE_ABSCISSA_1[index])),
            2 => Ok((HERMITE_WEIGHT_2[index], HERMITE_ABSCISSA_2[index])),
            3 => Ok((HERMITE_WEIGHT_3[index], HERMITE_ABSCISSA_3[index])),
            4 => Ok((HERMITE_WEIGHT_4[index], HERMITE_ABSCISSA_4[index])),
            5 => Ok((HERMITE_WEIGHT_5[index], HERMITE_ABSCISSA_5[index])),
            6 => Ok((HERMITE_WEIGHT_6[index], HERMITE_ABSCISSA_6[index])),
            7 => Ok((HERMITE_WEIGHT_7[index], HERMITE_ABSCISSA_7[index])),
            8 => Ok((HERMITE_WEIGHT_8[index], HERMITE_ABSCISSA_8[index])),
            9 => Ok((HERMITE_WEIGHT_9[index], HERMITE_ABSCISSA_9[index])),
            10 => Ok((HERMITE_WEIGHT_10[index], HERMITE_ABSCISSA_10[index])),
            11 => Ok((HERMITE_WEIGHT_11[index], HERMITE_ABSCISSA_11[index])),
            12 => Ok((HERMITE_WEIGHT_12[index], HERMITE_ABSCISSA_12[index])),
            13 => Ok((HERMITE_WEIGHT_13[index], HERMITE_ABSCISSA_13[index])),
            14 => Ok((HERMITE_WEIGHT_14[index], HERMITE_ABSCISSA_14[index])),
            15 => Ok((HERMITE_WEIGHT_15[index], HERMITE_ABSCISSA_15[index])),
            16 => Ok((HERMITE_WEIGHT_16[index], HERMITE_ABSCISSA_16[index])),
            17 => Ok((HERMITE_WEIGHT_17[index], HERMITE_ABSCISSA_17[index])),
            18 => Ok((HERMITE_WEIGHT_18[index], HERMITE_ABSCISSA_18[index])),
            19 => Ok((HERMITE_WEIGHT_19[index], HERMITE_ABSCISSA_19[index])),
            20 => Ok((HERMITE_WEIGHT_20[index], HERMITE_ABSCISSA_20[index])),
            21 => Ok((HERMITE_WEIGHT_21[index], HERMITE_ABSCISSA_21[index])),
            22 => Ok((HERMITE_WEIGHT_22[index], HERMITE_ABSCISSA_22[index])),
            23 => Ok((HERMITE_WEIGHT_23[index], HERMITE_ABSCISSA_23[index])),
            24 => Ok((HERMITE_WEIGHT_24[index], HERMITE_ABSCISSA_24[index])),
            25 => Ok((HERMITE_WEIGHT_25[index], HERMITE_ABSCISSA_25[index])),
            26 => Ok((HERMITE_WEIGHT_26[index], HERMITE_ABSCISSA_26[index])),
            27 => Ok((HERMITE_WEIGHT_27[index], HERMITE_ABSCISSA_27[index])),
            28 => Ok((HERMITE_WEIGHT_28[index], HERMITE_ABSCISSA_28[index])),
            29 => Ok((HERMITE_WEIGHT_29[index], HERMITE_ABSCISSA_29[index])),
            30 => Ok((HERMITE_WEIGHT_30[index], HERMITE_ABSCISSA_30[index])),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
        GaussianQuadratureMethod::GaussLegendre => match order {
            1 => Ok((LEGENDRE_WEIGHT_1[index], LEGENDRE_ABSCISSA_1[index])),
            2 => Ok((LEGENDRE_WEIGHT_2[index], LEGENDRE_ABSCISSA_2[index])),
            3 => Ok((LEGENDRE_WEIGHT_3[index], LEGENDRE_ABSCISSA_3[index])),
            4 => Ok((LEGENDRE_WEIGHT_4[index], LEGENDRE_ABSCISSA_4[index])),
            5 => Ok((LEGENDRE_WEIGHT_5[index], LEGENDRE_ABSCISSA_5[index])),
            6 => Ok((LEGENDRE_WEIGHT_6[index], LEGENDRE_ABSCISSA_6[index])),
            7 => Ok((LEGENDRE_WEIGHT_7[index], LEGENDRE_ABSCISSA_7[index])),
            8 => Ok((LEGENDRE_WEIGHT_8[index], LEGENDRE_ABSCISSA_8[index])),
            9 => Ok((LEGENDRE_WEIGHT_9[index], LEGENDRE_ABSCISSA_9[index])),
            10 => Ok((LEGENDRE_WEIGHT_10[index], LEGENDRE_ABSCISSA_10[index])),
            11 => Ok((LEGENDRE_WEIGHT_11[index], LEGENDRE_ABSCISSA_11[index])),
            12 => Ok((LEGENDRE_WEIGHT_12[index], LEGENDRE_ABSCISSA_12[index])),
            13 => Ok((LEGENDRE_WEIGHT_13[index], LEGENDRE_ABSCISSA_13[index])),
            14 => Ok((LEGENDRE_WEIGHT_14[index], LEGENDRE_ABSCISSA_14[index])),
            15 => Ok((LEGENDRE_WEIGHT_15[index], LEGENDRE_ABSCISSA_15[index])),
            16 => Ok((LEGENDRE_WEIGHT_16[index], LEGENDRE_ABSCISSA_16[index])),
            17 => Ok((LEGENDRE_WEIGHT_17[index], LEGENDRE_ABSCISSA_17[index])),
            18 => Ok((LEGENDRE_WEIGHT_18[index], LEGENDRE_ABSCISSA_18[index])),
            19 => Ok((LEGENDRE_WEIGHT_19[index], LEGENDRE_ABSCISSA_19[index])),
            20 => Ok((LEGENDRE_WEIGHT_20[index], LEGENDRE_ABSCISSA_20[index])),
            21 => Ok((LEGENDRE_WEIGHT_21[index], LEGENDRE_ABSCISSA_21[index])),
            22 => Ok((LEGENDRE_WEIGHT_22[index], LEGENDRE_ABSCISSA_22[index])),
            23 => Ok((LEGENDRE_WEIGHT_23[index], LEGENDRE_ABSCISSA_23[index])),
            24 => Ok((LEGENDRE_WEIGHT_24[index], LEGENDRE_ABSCISSA_24[index])),
            25 => Ok((LEGENDRE_WEIGHT_25[index], LEGENDRE_ABSCISSA_25[index])),
            26 => Ok((LEGENDRE_WEIGHT_26[index], LEGENDRE_ABSCISSA_26[index])),
            27 => Ok((LEGENDRE_WEIGHT_27[index], LEGENDRE_ABSCISSA_27[index])),
            28 => Ok((LEGENDRE_WEIGHT_28[index], LEGENDRE_ABSCISSA_28[index])),
            29 => Ok((LEGENDRE_WEIGHT_29[index], LEGENDRE_ABSCISSA_29[index])),
            30 => Ok((LEGENDRE_WEIGHT_30[index], LEGENDRE_ABSCISSA_30[index])),
            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),
        },
    }
}
