#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod approximation;
mod control;
mod discretization;
mod estimation;
mod gaussian_tables;
mod kinematics;
mod linear_algebra;
mod motion;
mod numerical_derivative;
mod numerical_integration;
mod ode;
mod optimization;
mod random;
mod root_finding;
mod scalar;
mod spatial;
mod utils;
mod vector_field;
