# This module is responsible for generating the lookup tables that the numerical integration crate uses.
# The autogenerated code is output inside src/gausian_tables.
# To manually regenerate the tables, run "python3 build_gaussian_integration_tables.py"

import os
from numpy.polynomial.laguerre import laggauss
from numpy.polynomial.hermite import hermgauss
from numpy.polynomial.legendre import leggauss

# Configuration
MAX_LENGTH = 31
methods = [
    ("GaussLaguerre", "laguerre", "LAGUERRE", laggauss),
    ("GaussHermite", "hermite", "HERMITE", hermgauss),
    ("GaussLegendre", "legendre", "LEGENDRE", leggauss),
]

# Ensure output directory exists
output_dir = "src/gaussian_tables"
os.makedirs(output_dir, exist_ok=True)

# Generate Rust files for each method
for _, module_name, const_prefix, func in methods:
    file_path = os.path.join(output_dir, f"{module_name}.rs")
    with open(file_path, "w") as f:
        f.write("// This file was auto-generated using scripts/build_gaussian_integration_tables.py\n// Do not edit manually.\n\n")

        for i in range(1, MAX_LENGTH):
            abs_values, weights = func(i)
            f.write(f"pub const {const_prefix}_ABSCISSA_{i}: [f64; {i}] = [\n")
            f.write(",\n".join(f"    {val:.16e}" for val in abs_values))
            f.write("\n];\n\n")
            f.write(f"pub const {const_prefix}_WEIGHT_{i}: [f64; {i}] = [\n")
            f.write(",\n".join(f"    {val:.16e}" for val in weights))
            f.write("\n];\n\n")

# Generate gauss.rs master module
gauss_path = os.path.join(output_dir, "gauss_tables.rs")
with open(gauss_path, "w") as f:
    f.write("// This file was auto-generated using scripts/build_gaussian_integration_tables.py\n// Do not edit manually.\n\n")
    f.write("use crate::utils::error_codes::GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE;\n\n")
    f.write("use crate::numerical_integration::mode::GaussianQuadratureMethod;\n\n")

    for _, module_name, _, _ in methods:
        f.write(f"use crate::gaussian_tables::{module_name}::*;\n")
    f.write("\n")

    f.write(f"pub const MAX_GAUSS_TABLE_ORDER: usize = {MAX_LENGTH-1};\n\n")

    # get_weights_and_abscissae function
    f.write("pub fn get_weight_and_abscissa(method: GaussianQuadratureMethod, order: usize, index: usize) -> Result<(f64, f64), &'static str> {\n")
    f.write("    match method {\n")
    for method_name, module_name, const_prefix, _ in methods:
        f.write(f"        GaussianQuadratureMethod::{method_name} => match order {{\n")
        for i in range(1, MAX_LENGTH):
            f.write(f"            {i} => Ok(({const_prefix}_WEIGHT_{i}[index], {const_prefix}_ABSCISSA_{i}[index])),\n")
        f.write("            _ => Err(GAUSSIAN_QUADRATURE_ORDER_OUT_OF_RANGE),\n")
        f.write("        },\n")
    f.write("    }\n")
    f.write("}\n")

# Generate mod.rs to include all generated modules
mod_rs_path = os.path.join(output_dir, "mod.rs")
with open(mod_rs_path, "w") as f:
    f.write("// Auto-generated module declarations\n\n")
    f.write("pub mod laguerre;\n")
    f.write("pub mod hermite;\n")
    f.write("pub mod legendre;\n")
    f.write("pub mod gauss_tables;\n")