#![allow(clippy::needless_return)]
#![allow(clippy::type_complexity)]

// #![no_std]

#[cfg(feature = "heap")]
extern crate std;

// autogenerated tables used for numerical gaussian integration
pub mod gaussian_tables;

pub mod approximation;
pub mod numerical_derivative;
pub mod numerical_integration;
pub mod utils;
pub mod vector_field;
